### PR TITLE
Use the new Lexicon-based plugin API

### PR DESCRIPTION
**Pull request by adferrand**
Hello!

You are maintaining a Lexicon-based DNS plugin for Certbot.

We released a new plugin API for these plugins since version 2.7.0. This new approach reduces a lot the complexity of the plugins by leveraging most of the instrumentation of Lexicon client in the new base class `certbot.plugins.dns_common_lexicon.LexiconDNSAuthenticator`. What remains essentially is the implementation of a couple of declarative properties in the final class, like the name of the Lexicon provider.

This PRs proposes the migration to this new API, as part of the global effort to help the community to shift to the new API. You can check https://github.com/certbot/certbot/issues/9776.

I am available for any question. Thanks you a lot in advance!

### CODE REVIEW

**Comment by miigotu** [comment]
@adferrand has this been tested with GoDaddy? Also (unrelated), is there an easy way to set this up for a snap build? I would be happy to add you or the certbot organization as contributors with write access to this project if interested, it might help as I don't have a ton of time for this plugin.

**Comment by miigotu** [comment]
I will have to wait until I am at a PC to fix some merge conflicts, this repository is fairly new and does not have some things set up to prevent conflicts.

**Comment by miigotu** [comment]
@adferrand the only thing I'm concerned about is the part where I customized lexicon's GoDaddy client, to correctly get the proper domain from accounts that had multiple domains registered for different locations. Otherwise there were issues creating and deleting records. 

```python
ex = tldextract.extract(domain)
self._find_domain_id(ex.registered_domain)
```

**Comment by adferrand** [comment]
Hello @miigotu!

So I have not tested it with GoDaddy, but I will be glad to do so if you have a temporary account to provide. In general this new approach has been tested with success on all Lexicon-based plugins that lies in certbot repository, so I am confident, and the only part that need to be verified are the customizations specific to a given plugin, more on this just after.

In term of documentation, setup etc., the changes are designed to be an opt-in migration. This new API, on top of reducing the amount of code needed, relies internally on the higher level of Lexicon client instead of the specific GoDaddy provider. But externally, nothing is modified, and the same CLI flags, configuration file and way to connect the plugin to Certbot is the same as before.

**Comment by adferrand** [comment]
About the customizations now.

Basically by calling `tldextract.extract` then `ex.registered_domain`, you strip out any subdomain in `domain`. For instance with `test.example.com`, you will get `example.com`. With `example.com` you will still get `example.com`. To understand why you have some failures without this code, I would need some examples. But here is my guess.

You need to know that the `_find_domain_id` uses a particular trick to workaround a problem we encountered several time. Basically you can have a domain, say `example.com` on a specific DNS zone, and a subdomain, say `test.example.com` on another DNS zone. Both DNS zone can even be in different DNS providers. Now the question is, how certbot and lexicon should guess that when asking a certificate for `*.test.example.com`, the DNS zone to operate is `test.example.com` and not `example.com`?

The answer we have currently is to test recursively the authentication against the API provider from the most specific to the less specific FQDN. So `_find_domain_id` will try to authenticate with `test.example.com` then `example.com`. This trick will work if the plugin is able to extract from any exception raised by Lexicon, the ones that correspond to the fact that the domain tested is not valid for these credentials. If so, the loop in `_find_domain_id` can stop on the proper domain (here, `test.example.com`).

So my guess here is that we are in a situation of a FQDN like `test.example.com` hosted on the zone `example.com`, and there is no DNS zone for `test.example.com`. Lexicon client raises an exception when testing authentication `test.example.com` and the plugin fails to catch the error, then the entire process breaks and there is no opportunity to test authentication with `example.com`. By calling your code, you strip out immediately the domain to `example.com` and everything works. But you close the door for situations were GoDaddy DNS zone actually hosts the subdomain.

**Comment by adferrand** [comment]
So there are several solutions here:
1) we keep things as before, by overriding the `_resolve_domain` to use directly tldextract
2) we implement the proper catching of the errors by overriding `_handle_general_error` as it is done in the other DNS plugins
3) I implement a proper resolution of the DNS zone domain in Lexicon (I do not like the mechanism described above, I would like to change it).

This is ordered from the shortest to the longest term. My personal preference is to do 1) right now, and I invest on 3). Once 3) is available, I come back here to do the changes.

What do you think of that?

**Pull request merged**
